[package]
name = "reactivate"
version = "0.4.2"
edition = "2021"
authors = ["Zahash <zahash.z@gmail.com>"]
description = "Thread Safe Reactive Data Structure. Made with â¤ï¸ for ğŸ¦€"
license = "MIT"
repository = "https://github.com/zahash/reactivate"

[dependencies]
paste = "1"


[features]
threadsafe = []
