[package]
name = "reactivate"
version = "0.2.10"
edition = "2021"
authors = ["Zahash <zahash.z@gmail.com>"]
description = "Thread Safe Reactive Data Structure. Made with â¤ï¸ for ğŸ¦€"
license = "MIT"
repository = "https://github.com/zahash/reactivate"

[dependencies]
paste = { version = "1" }
